# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657f1e8c16f11e91424c1175c1edf6e285142cb67d43477d0f869a53fe5b0fa86fda6b2b5cf008a241bcb30de53594939463021852acd495f180b30f2b6a97d5

test:
  secret_key_base: e933184acad42b53fc4eaabd48c9af76cf208c8d23545fc7873073d3d0e7a4a45b5f4ccfd955bb4f24e1c12346c15625cc83c942e09a0a8c4761fc7f470fc619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
